### ISSUE TITLE
cant find frozen_inference_graph.pb

### ISSUE THREAD

**Issue by melikavhf** [DavidTorresOcana/ros_object_detector#1]
![f](https://user-images.githubusercontent.com/24391257/40662957-369b89a6-6347-11e8-8534-8f79af64c59c.png)

but I have this file

![d](https://user-images.githubusercontent.com/24391257/40663017-56f029be-6347-11e8-828c-7c809f985bd9.png)

what should I do?

**Comment by DavidTorresOcana** [comment]
Hello
It was a bug, try with  [1a34c03 ](https://github.com/DavidTorresOcana/ros_object_detector/commit/1a34c03e484172f7bbf88f7b5c569194fa8d2a45)

Regards
