### ISSUE TITLE
ERROR: cannot launch node of type (dont create anything in lib/ros_object_detector)

### ISSUE THREAD

**Issue by melikavhf** [DavidTorresOcana/ros_object_detector#3]
hello .
The process is very high .This is my system information
processor Intel® Core™ i5-6200U CPU @ 2.30GHz × 4 
graphic Intel® HD Graphics 520 (Skylake GT2) 
memory 7.7 GiB

What can I do to reduce the process?
![process](https://user-images.githubusercontent.com/24391257/41247426-3341cdc0-6dc3-11e8-8e03-c06e45d3f24e.png)

**Comment by DavidTorresOcana** [comment]
Hello

I would suggest you to use Tensorflow for GPU: See here how to install it: https://www.tensorflow.org/install/install_linux

Regards

**Comment by melikavhf** [comment]
Thanks for reply
I have no gpu . what should I do?

**Comment by DavidTorresOcana** [comment]
Hello

Sorry, there is little you can do then. You can try reduce the FPS

Regards

**Comment by melikavhf** [comment]
Hello
Where can I find FPS ??
tensorflow-gpu just support nvidia gpu
