### ISSUE TITLE
Z-axis

### ISSUE THREAD

**Issue by iamMHZ** [DavidTorresOcana/ros_object_detector#4]
Hi

How to get Z-axis of objects ??

![image](https://user-images.githubusercontent.com/45208866/68478768-f420a300-0245-11ea-94ec-30ac594c26c1.png)
`

**Comment by DavidTorresOcana** [comment]
This is just a wrapper of a CNN based 2D object detector. Hence, it is not possible to get depth to object.

**Comment by iamMHZ** [comment]
aha 

anyway
How is it possible to get depth of objects??
What are the tools  and  ways ??

**Comment by DavidTorresOcana** [comment]
That is beyond the scope of this project, I am afraid.

This project is simply a ROS wrapper around a CNN.
